spring.application.name=revise

server.port=8686

spring.datasource.url=jdbc:mysql://localhost:3306/hit_springboot
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
#Cho phép gom 50 câu l?nh insert/update l?i r?i g?i ?i m?t l?n ?? t?ng t?c hi?u n?ng.

#Cau hinh JSON
spring.jackson.serialization.indent-output=true
#JSON tra ve co thut le
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#Quy ??nh ??nh d?ng ngày tháng hi?n th? là N?m-Tháng-Ngày Gi?:Phút:Giây
spring.jackson.time-zone=Asia/Ho_Chi_Minh
#Thi?t l?p múi gi? Vi?t Nam.

#SWAGGER
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true



#Ch? hi?n các thông báo quan tr?ng c?a h? th?ng.
logging.level.root=INFO

#: Hi?n chi ti?t các ho?t ??ng trong package code c?a b?n (giúp tìm l?i d? h?n).
logging.level.com.hit.springboot=DEBUG

#: M?c ?? cao nh?t, cho phép b?n nhìn th?y c? các giá tr? th?c t? mà b?n truy?n vào câu l?nh SQL (ví d?: th?y ???c username là gì khi insert).
logging.level.org.hibernate.orm.jdbc.bind=TRACE
