spring.application.name=demolession02

# === Server ===
server.port=8080                  

# === Logging ===
logging.level.root=INFO            
logging.level.com.example.demo=DEBUG 

# === JSON Output ===
spring.jackson.serialization.indent-output=true  

spring.web.error.include-message=always
